apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: default-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: my-kafka
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: persistent-claim
    size: 10Gi
    deleteClaim: false
